name:                etanol
version:             0.1.0.0
github:              "mbrc12/etanol"
license:             BSD3
author:              "Mriganka Basu Roy Chowdhury"
maintainer:          "mbrc12@gmail.com"
copyright:           "2018 Mriganka Basu Roy Chowdhury"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mbrc12/etanol#readme>

dependencies:
- base >= 4.7 && < 5
- fgl  >= 5.6
- directory >= 1.3
- filepath >= 1.4
- containers >= 0.5.10
- cereal >= 0.5.5
library:
  source-dirs: src

executables:
  etanol-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - etanol

tests:
  etanol-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - etanol
