version: 2
dependencies:
    pre: 
        - sudo apt-get update; sudo apt-get install curl
jobs:
  build:
    docker:
      - image: docker:17.06.1-ce-git
    steps:
      - checkout 
      - run:
          name: Install curl
          command: apk update && apk add curl curl-dev bash
      - run:
          name: Download and install stack
          command: curl -sSL https://get.haskellstack.org/ | sh
      - run:
          name: Check stack version
          command: stack --version
