version: 2

jobs:
  build:
    docker:
      - image: fpco/stack-build:latest   
    steps:
      - checkout 
      - run: git submodule sync
      - run: git submodule update --init --recursive
     
      - run: mkdir TestSuite
      
      - run: wget https://github.com/mbrc12/test-suites/raw/master/TestSuite/etanol/guava-23.0.jar -O TestSuite/guava.jar
      - run: wget https://github.com/mbrc12/test-suites/raw/master/TestSuite/etanol/rt_java7.jar -O TestSuite/rt7.jar
      - run: wget https://github.com/mbrc12/test-suites/raw/master/TestSuite/etanol/rt_java8.jar -O TestSuite/rt8.jar
      
      - run: mkdir TestSuite/guava
      - run: mkdir TestSuite/rt7
      - run: mkdir TestSuite/rt8
      
      - run: unzip TestSuite/guava.jar -d TestSuite/guava/
      - run: unzip TestSuite/rt7.jar -d TestSuite/rt7/
      - run: unzip TestSuite/rt8.jar -d TestSuite/rt8/

      - run: mkdir Output

      - run:
          name: Build
          command: stack build

      - run:
          name: Test - Benchmark 1
          command: stack exec -- etanolx -a TestSuite/rt7/ -s "" -o Output/rt7.db
      - run:
          name: Test - Benchmark 2
          command: stack exec -- etanolx -a TestSuite/rt8/ -s "" -o Output/rt8.db
      - run:
          name: Test - Benchmark 3
          command: stack exec -- etanolx -a TestSuite/guava/ -s "Output/rt8.db" -o Output/guava.db
      
      - store_artifacts:
          path: Output/
     
