version: 2
dependencies:
    pre: 
        - sudo apt-get update; sudo apt-get install curl
jobs:
  build:
    docker:
      - image: fpco/stack-build:latest   
    steps:
      - checkout 
#- run:
#          name: Install curl
#          command: apk update && apk add curl curl-dev bash
#      - run:
#          name: CA Certificates
#          command: apk add ca-certificates && update-ca-certificates
          

#      - run: wget https://github.com/commercialhaskell/stack/releases/download/v1.7.1/stack-1.7.1-linux-x86_64.tar.gz -O /tmp/stack.tar.gz
#      - run: mkdir /tmp/stack
#      - run: tar -xvf /tmp/stack.tar.gz -C /tmp/stack/
#      - run: sudo chmod +x /tmp/stack/stack-1.7.1-linux-x86_64/stack
#      - run: sudo mv /tmp/stack/stack-1.7.1-linux-x86_64/stack /usr/bin/stack

      - run:
          name: Check stack version
          command: stack --version
      - run:
          name: Build
          command: stack build
