version: 2

jobs:
  build:
    docker:
      - image: fpco/stack-build:latest   
    steps:
      - checkout 
      - run: git submodule sync
      - run: git submodule update --init --recursive
     
      - run: mkdir TestSuite
      
      - run: wget http://central.maven.org/maven2/com/google/guava/guava/23.0/guava-23.0.jar -O TestSuite/guava.jar
      - run: wget https://cdnverify.eta-lang.org/eta-binaries/etanol/rt_java7.jar -O TestSuite/rt7.jar
      - run: wget https://cdnverify.eta-lang.org/eta-binaries/etanol/rt_java8.jar -O TestSuite/rt8.jar
      #- run: wget  -O ~/.etanol/config
      
      - run: mkdir TestSuite/guava
      - run: mkdir TestSuite/rt7
      - run: mkdir TestSuite/rt8
      
      - run: unzip TestSuite/guava.jar -d TestSuite/guava/
      - run: unzip TestSuite/rt7.jar -d TestSuite/rt7/
      - run: unzip TestSuite/rt8.jar -d TestSuite/rt8/

      - run: mkdir Output

      - run:
          name: Build
          command: stack build

      - run:
          name: Test 1, rt 7's java.lang
          command: stack exec -- etanolx -a TestSuite/rt7/java/lang/ -s "" -o Output/rt7javalang.db
      - run:
          name: Test 2, rt 8's java
          command: stack exec -- etanolx -a TestSuite/rt8/java/ -s "" -o Output/rt8java.db
      - run:
          name: Test 3, rt 8's javax
          command: stack exec -- etanolx -a TestSuite/rt8/javax/ -s "Output/rt8java.db" -o Output/rt8javax.db
      - run:
          name: Test 4, Guava
          command: stack exec -- etanolx -a TestSuite/guava/ -s "Output/rt8java.db  Output/rt8javax.db" -o Output/guava.db
      
      - store_artifacts:
          path: Output/
     
